### ISSUE TITLE
DatePIcker - date invalide sauvegardée

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic-DSFR#185]
A la saisie d'une date invalide (31.11.2024 par exemple), la donnée en Lunatic n'est pas sauvegardée, mais elle est l'est dans la version Dsfr du composant

=> faire en sorte que les dates invalides ne soient pas sauvegardées.

**Comment by laurentC35** [comment]
Trouver mieux pour avoir un retour utilisateur.

L'utilisateur n'a pas l'info que la date saisie est incorrecte

**Comment by ddecrulle** [comment]
Waiting for @romaintailhurat investigations on VTL solution to check valide date inside controls

**Comment by ddecrulle** [comment]
Using the `cast` function to convert a string to a date automatically corrects any invalid dates (e.g., if the specified day does not exist in the given month). For example:

```vtl
cast("1998-02-30", date, "YYYY-MM-DD" )
```
returns: `"1998-03-02"`.

However, if the date is invalid due to an incorrect month or format, such as "2000-13-01", the cast function will fail and result in an error.

We can deduce if a date is valid or not in VTL with this expression:
```vtl
# Given a string value DATE ex: "1998-03-02"
cast(cast(DATE, date, "YYYY-MM-DD"), string , "YYYY-MM-DD") = DATE
```
It will return true if the date is valid, and false otherwise.

This approach is a VTL workaround; there may be native VTL functions available, but they are not yet implemented in [Trevas-JS](https://github.com/InseeFr/Trevas-JS).

Take in mind that the cast into date may failed  (for example "2000-13-01" will leads to an error).

**Comment by AnneHuSKa** [comment]
@ddecrulle I think this is an excellent solution! 
However, the formula doesn't seem to work in the way we could process it: we can test cast(cast(DATE, date, "YYYY-MM-DD"), string , "YYYY-MM-DD") = DATE but cast(DATE, date, "YYYY-MM-DD"), string , "YYYY-MM-DD") <> DATE doesn't return an error, 


[issue185.json](https://github.com/user-attachments/files/16412598/issue185.json)

**Comment by ddecrulle** [comment]
I just tested the survey you attached, it's seems to work for me ? 

<img width="876" alt="image" src="https://github.com/user-attachments/assets/46befca5-740a-4443-aa90-2240ad25d093">

**Comment by AnneHuSKa** [comment]
It works with Edge but not with Firefox :
![image](https://github.com/user-attachments/assets/55f5a2b3-c3d5-4849-86e1-2b62d0f966bd)
against 
![image](https://github.com/user-attachments/assets/1fc02ab1-d4ae-4c80-a0e2-3b2544ea7cc2)

**Comment by ddecrulle** [comment]
I also tested on firefox and it works on my laptop ...

<img width="1288" alt="image" src="https://github.com/user-attachments/assets/2d6e0e70-9f81-45b1-b069-4e9db3f9f569">

**Comment by ddecrulle** [comment]
Can you give me the data (logged when clicking on "Get Data") so i can debug ?

**Comment by AnneHuSKa** [comment]
[data185.txt](https://github.com/user-attachments/files/16427166/data185.txt)
